# This is the name of your Cloudflare Pages project.
name = "Björns-mattebilder"

# This specifies that you are deploying a static site.
[site]
bucket = "./dist"

# This is a compatibility date to ensure the latest features are used.
# It is a good practice to use the current date.
compatibility_date = "2025-08-26"